impl manage following
sivchari/gotwtr pull request #112
Opened 2021-12-17 07:37 UTC by mmmommm

ref #108

2021-12-18 14:23 UTC, sivchari commented
Please update push target to dev-1.1. After that, I check your PR.

2021-12-19 02:37 UTC, mmmommm commented
@sivchari 
I fixed it, please review.

2021-12-19 02:47 UTC, mmmommm commented
Wait until user API example is added to `example_test.go`

2021-12-21 02:12 UTC, sivchari requested changes

2021-12-21 02:12 UTC, sivchari commented on client.go
> +	UndoFollowing(ctx context.Context, suid string, tuid string) (*UndoFollowingResponse, error)
I think some parameters (e.g. tuid, id) are not clearly.
This args are shown user. So, we must define arg name more meaningful.

2021-12-21 02:12 UTC, sivchari commented on follow.go
> +		return nil, errors.New("post following by id: id parameter is required")
```suggestion
		return nil, errors.New("post following by id: id parameter is required")
```

I think ID is not clearly.

2021-12-22 06:16 UTC, sivchari requested changes

2021-12-22 06:16 UTC, sivchari commented on example/user/follow/main.go
> +	fmt.Println(d)
These code must been moved to ExampleXXX.

2021-12-22 06:16 UTC, sivchari commented on follow.go
> +		return nil, errors.New("undo following by sourceUserID: sourceUserID parameter is required")
I think this error message isn't good.
This is because some of the error messages are duplicated.

2021-12-22 06:16 UTC, sivchari commented on follow_test.go
> +		},
Please add more test case.

2021-12-22 06:16 UTC, sivchari commented on follow_test.go
> +	}
Same as above.

2022-01-02 10:14 UTC, sivchari approved these changes
LGTM

2022-01-02 10:14 UTC, merged