Impl user timeline
sivchari/gotwtr pull request #18
Opened 2021-10-04 07:35 UTC by mmmommm

Add user timeline APIs

2021-10-04 08:04 UTC, sivchari requested changes
Please change.

2021-10-04 08:04 UTC, sivchari commented on tweet.go
> +}
This method is already defined at tweet_option.go
If you wanna define option's method, please write at it.

2021-10-04 08:04 UTC, sivchari commented on tweet.go
> +	return slice
Same reason as above.

2021-10-04 08:04 UTC, sivchari commented on user.go
> +	UserName string `json:"username"`
Thanks a lot.

2021-10-04 12:34 UTC, mmmommm commented on tweet_option.go
> +	Excludes        []Exclude
![スクリーンショット 2021-10-04 21 29 44](https://user-images.githubusercontent.com/51479834/135851506-daeab93b-7439-4f84-9df3-8d2c13e97a63.png)

@sivchari 
From twitter api documentation,`Exclude` is correct for this field name, but the array is the correct one to put here, what do you think it should be called?

2021-10-04 15:26 UTC, sivchari commented on tweet_option.go
> +	Excludes        []Exclude
This field can be one or two, so I want to name the field Exclude.

2021-10-05 02:59 UTC, sivchari commented
Good work, thanks !

2021-10-05 04:59 UTC, sivchari commented
Please rebase 👍  I fixed workflow.
If you rebase and push, reviewdog annotates your syntax error.

2021-10-05 06:42 UTC, sivchari commented
please check file changes.

2021-10-05 07:29 UTC, sivchari approved these changes

2021-10-05 07:30 UTC, merged