Impl user follows
sivchari/gotwtr pull request #61
Opened 2021-11-04 21:55 UTC by mmmommm

close #54

2021-11-04 21:58 UTC, mmmommm commented on retweets.go
> +	req.Header.Set("Authorization", fmt.Sprintf("OAuth %s", c.bearerToken))
I've mixed up the correction of a mistake in a previous retweet pr.
F.Y.I https://developer.twitter.com/en/docs/twitter-api/tweets/retweets/api-reference/post-users-id-retweets

2021-11-09 02:57 UTC, sivchari requested changes

2021-11-09 02:57 UTC, sivchari commented on client.go
> +	// DeleteFollowing(ctx context.Context, suid string, tuid string) (*DeleteFollowingResponse, error)
```suggestion
	// UndoFollowing(ctx context.Context, suid string, tuid string) (*DeleteFollowingResponse, error)
```

2021-11-09 02:57 UTC, sivchari commented on client.go
> +func (c *client) DeleteFollowing(ctx context.Context, suid string, tuid string) (*DeleteFollowingResponse, error) {
```suggestion
func (c *client) UndoFollowing(ctx context.Context, suid string, tuid string) (*DeleteFollowingResponse, error) {
```

2021-11-09 02:57 UTC, sivchari commented on client.go
> +	// DeleteRetweet(ctx context.Context, id string, stid string) (*DeleteRetweetResponse, error)
```suggestion
	// UndoRetweet(ctx context.Context, id string, stid string) (*DeleteRetweetResponse, error)
```

2021-11-09 02:57 UTC, sivchari commented on client.go
>  func (c *client) DeleteRetweet(ctx context.Context, id string, stid string) (*DeleteRetweetResponse, error) {
```suggestion
func (c *client) UndoRetweet(ctx context.Context, id string, stid string) (*DeleteRetweetResponse, error) {
```

2021-11-09 04:26 UTC, sivchari approved these changes
LGTM

2021-11-09 04:26 UTC, merged